### ISSUE TITLE
Add `$gutter: center` modifier

### ISSUE THREAD

**Issue by ezekg** [ezekg/flint#22]
Add ability to center columns with `$gutter: center`. Found myself doing this as a workaround:

``` scss
@include _(4) {
    margin: 0 auto;
}
```
